on:
  push:
    branches:
      - main
    paths:
      - 'api_service/**'

jobs:

  build:
    name: Deploy to DO Droplet
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Container and auto-tag them
        run: docker build -t nikoisonfire/podcastpill_api .  && docker tag nikoisonfire/podcastpill_api:latest nikoisonfire/podcastpill_api:latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image to DockerHub
        run: docker push nikoisonfire/podcastpill_api:latest

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22
          script: |
            docker stop nikoisonfire/podcastpill_api || true
            docker rm nikoisonfire/podcastpill_api || true
            docker pull nikoisonfire/podcastpill_api:latest
            docker run -d --name podcastpill_api -p 80:80 nikoisonfire/podcastpill_api:latest
